export enum TRANSACTION_TYPE {
    BUY = "BUY",
    SELL = "SELL",
    FUEL = "FUEL",
    PALTI = "PALTI",
    WEIGHT_LOSS = "WEIGHT_LOSS",
    SHOP_BUY = "SHOP_BUY",
    DEBIT_NOTE = "DEBIT_NOTE",
    CREDIT_NOTE = "CREDIT_NOTE",
    SALARY_PAYMENT = "SALARY_PAYMENT",
    ADVANCE_PAYMENT = "ADVANCE_PAYMENT",
    RECEIVE_PAYMENT = "RECEIVE_PAYMENT",
    PAYMENT_TO_COMPANY = "PAYMENT_TO_COMPANY",
    PAYMENT_TO_BANK = "PAYMENT_TO_BANK",
    PAYMENT_TO_EXPENSE = "PAYMENT_TO_EXPENSE",
    PAYMENT_TO_OTHER = "PAYMENT_TO_OTHER",
    CASH_TO_BANK = "CASH_TO_BANK",
    BANK_TO_BANK = "BANK_TO_BANK",
}

export enum TRANSACTION_SUB_TYPE {
    MORTALITY = "MORTALITY",
    WASTE = "WASTE",
    OTHER = "OTHER",
}